# .air.toml for Go Sentinel
root = "."
tmp_dir = "tmp"

[build]
  # First run linter, then build the binary
  pre_cmd = [
    "golangci-lint run --timeout=2m"
  ]
  cmd = "go build -o ./tmp/main.exe ./cmd/go-sentinel-web"
  bin = "./tmp/main.exe"
  # Stop if linting fails
  stop_on_error = true
  # Show error message in terminal
  error_length = 10000

[run]
# run the binary
  cmd = "./tmp/main.exe"

[watch]
  delay = 1000
  # Be more specific about what to watch
  includes = [
    # Go files
    "./cmd/**/*.go",
    "./internal/**/*.go",
    "./pkg/**/*.go",
    # Web files
    "./web/templates/**/*.tmpl",
    "./web/static/css/**/*.css",
    "./web/static/js/src/**/*.ts",
    "./web/static/js/src/**/*.js",
    # Config files
    "./*.json",
    "./*.yaml",
    "./*.toml"
  ]
  # Exclude patterns - order matters, excludes are processed first
  excludes = [
    # Dependencies and version control
    "./web/static/js/node_modules",
    "./web/static/js/node_modules/**",
    "./.git",
    "./.git/**",
    "./vendor",
    "./vendor/**",
    # Build artifacts and temp files
    "./tmp",
    "./tmp/**",
    "./dist",
    "./dist/**",
    "./build",
    "./build/**",
    "**/*.exe",
    "**/*.test",
    "**/*.out",
    # Test files
    "**/*_test.go",
    "**/testdata",
    "**/testdata/**",
    # Coverage files
    "**/coverage",
    "**/coverage/**",
    "**/*.coverage.*"
  ]
  # File extensions to watch
  extensions = ["go", "tmpl", "css", "js", "ts", "json", "yaml", "toml"]

[log]
  color = true
  time = true
  level = "debug" # debug, info, warn, error

[misc]
  # clean the tmp directory on exit
  clean_on_exit = true



