run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - unconvert
    - gosec
    - unparam

linters-settings:
  govet:
    check-shadowing: true
  
  gosec:
    includes:
      - G101-G505

issues:
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
