run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - unconvert
    - gosec
    - unparam
    - gocyclo
    - gocognit
    - funlen

linters-settings:
  govet:
    check-shadowing: true

  gosec:
    includes:
      - G101-G505

  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 10

  funlen:
    lines: 50
    statements: 30

issues:
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
