repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: Go Format
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$
        
      - id: go-imports
        name: Go Imports
        entry: goimports
        language: system
        args: [-w]
        files: \.go$
        
      - id: go-vet
        name: Go Vet
        entry: go
        language: system
        args: [vet, ./...]
        files: \.go$
        pass_filenames: false
        
      - id: go-mod-tidy
        name: Go Mod Tidy
        entry: go
        language: system
        args: [mod, tidy]
        files: go\.(mod|sum)$
        pass_filenames: false
        
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        args: [run, --config=.golangci.yml, --new-from-rev=HEAD~1]
        files: \.go$
        pass_filenames: false
        
      - id: go-tests
        name: Go Tests
        entry: go
        language: system
        args: [test, -race, -short, ./...]
        files: \.go$
        pass_filenames: false
        
      - id: go-security
        name: Go Security (gosec)
        entry: bash
        language: system
        args: [-c, 'if ! command -v gosec &> /dev/null; then go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest; fi && gosec ./...']
        files: \.go$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: detect-private-key
      - id: check-case-conflict
      - id: mixed-line-ending
        
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [-i, '2', -w]
        files: \.(sh|bash)$
      - id: shellcheck
        files: \.(sh|bash)$

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
